# Generated by Django 5.2.9 on 2025-12-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_tasks_task_status_d27f27_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_status_d27f27_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_created_69a8b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_created_5da2cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_status_da2428_idx',
        ),
    ]
